### ISSUE TITLE
Yêu cầu chức năng

### ISSUE THREAD

**Issue by LongTran0919** [LongTran0919/GymWeb#3]

**Comment by trangiaphuc** [comment]
User Requirement:
Lập trình 1 web có thể xem, tìm học các bài tập Gym phù hơp giúp cải thiện vóc dáng, đồng thời có thể theo dõi tình trạng sức khỏe thông qua chỉ số BMI của bản thân

**Comment by trangiaphuc** [comment]
System Requirement:
1. User được tạo 1 tài khoản cá nhân, user có thể thêm các khóa học yêu thích vào wishlist để thuận tiện xem và tập luyện.
Ở thông tin cá nhân, user có thể nhập dữ liệu về cân nặng và chiều cao để có thể theo dõi chỉ số BMI của bản thân thông qua quá trình tập luyện, theo dõi thời gian tập luyện, số lần tập luyện của bản thân

**Comment by trangiaphuc** [comment]
2. Admin thực hiện hoạt động post các bài viết cung cấp các thông tin về các bài tập Gym, các chế độ ăn uống khi tập, người xem nhận thông tin và có các phản hồi về bài viết

**Comment by LongTran0919** [comment]
3. User có thể tìm kiếm bài tập thích hợp để tập luyện theo thông qua các từ khóa mà user nhập vào.

**Comment by LongTran0919** [comment]
4. Hiển thị thông tin user trong phần profile, các thông tin đó được user nhập khi đăng ký.

**Comment by LongTran0919** [comment]
5. Xem bài tập
