### ISSUE TITLE
Phân tích đặc tả, vẽ lược đồ usecase, sequence, class

### ISSUE THREAD

**Issue by tandev151** [LongTran0919/GymWeb#33]

**Comment by LongTran0919** [comment]
https://drive.google.com/file/d/1ZYn09SwEk3-Lrse1_wrOjJSYWl1C3eaV/view?usp=sharing
Class Diagram

**Comment by LongTran0919** [comment]
https://drive.google.com/file/d/1-aHYgffdKrNc59qy7Ik5mSmErEh4mjLb/view?usp=sharing
Theo dỗi chỉ số BMI

**Comment by LongTran0919** [comment]
https://drive.google.com/file/d/1Xu3Ak27zqhYqdHaUBWJTNms7gTQ5kzaq/view?usp=sharing
Đăng nhập

**Comment by LongTran0919** [comment]
https://drive.google.com/file/d/1HPrBn0pouX-hIDE8fnMunwaRMCyLROAY/view?usp=sharing
Đăng kí

**Comment by LongTran0919** [comment]
https://drive.google.com/file/d/1LwVysEhVs9ljcvtvw3yyoJ671WljQdvJ/view?usp=sharing
Xem bài tập

**Comment by LongTran0919** [comment]
https://drive.google.com/file/d/1WweRjWbAz5QkLfmRZpfA_7-7C5uRFGXY/view?usp=sharing
Quản lý thông tin bài tập

**Comment by LongTran0919** [comment]
https://drive.google.com/file/d/1BUMSAFZQF9YbtISaJrs7CV9ftNu4Drxd/view?usp=sharing
Tra cứu

**Comment by LongTran0919** [comment]
https://drive.google.com/file/d/1GUbMUau5eOlZnM8ibjJXeCWk-OaIqT6a/view?usp=sharing
Kế hoạch luyện tập
