### ISSUE TITLE
Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by LongTran0919** [LongTran0919/GymWeb#4]
Các yêu cầu phi chức năng

**Comment by dajneem23** [comment]
Các yêu cầu phi chức năng:
-Giao diện yêu cầu thể hiện rõ ràng, bố cục hợp lý dễ sử dụng.
-Ngôn ngữ sử dụng : Java

**Comment by dajneem23** [comment]
sử dụng api web java servlet 
- kết nối với cơ sở dữ liệu.
- thể hiện lên UI.
- tốc độ phản hồi nhanh.
-  thể hiện đúng nội dung.

**Comment by dajneem23** [comment]
Bảo mật:
- sử dụng giao thức bảo mật https mã hóa và lưu trữ  mật khẩu ở database dưới dạng hash
-  có xác thực otp.
- tránh các lỗi như : xss,sqli, xxe,....

**Comment by dajneem23** [comment]
- thời gian đăng nhập dưới 2s/người.
- có sức chịu tải ít nhất 1000 người sử dụng cùng một thời điểm.
- có khả năng chịu lỗi phục hồi khi gặp sự cố,
